spring:
  application:
    name: oauth-server

server:
  port: 8081
  context-path: /spring-security-oauth-server

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost